### ISSUE TITLE
error when subset <- pe["AALEELVK",colData(pe)$lab=="lab1"]

### ISSUE THREAD

**Issue by ncasiraghi** [statOmics/PDA21#1]
Hi, I'm following step-by-step the [tutorial](https://statomics.github.io/PDA21/pda_quantification_preprocessing.html#311_Explore_the_data_with_plots) but I fail in build the `subset` object since it seems that `colData(pe)$lab` is `NULL`. Indeed `colData(pe)` returns `DataFrame with 45 rows and 0 columns`

Thanks a lot for any helps.

**Comment by lievenclement** [comment]
Dear Nicola

This was also mentioned in section 2.2.3 explore object and then we define the colData. You probably missed it because the output of the rowData is so large. The part where we define the colData is just below the output of the rowData in section 2.2.3 and above section 3 preprocessing.

Does this work for you?

Best

Lieven

**Comment by ncasiraghi** [comment]
Alright, my bad. Found it, thanks!
